/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.FetchAdminAnalytics;
import model.FetchFilesDataForTable;
import model.FetchReportedUserData;
import model.FetchUserDataForTable;

/**
 *
 * @author jaint
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        notificationBTN = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        notificationCountValue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalNumberOfBannedUser = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalNumberOfUser = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalNumberOfFilesUploaded = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(16, 23, 39));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("All Users");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(75, 158, 119, 38);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("All Files");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(75, 235, 119, 38);

        notificationBTN.setBackground(new java.awt.Color(51, 51, 51));
        notificationBTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        notificationBTN.setForeground(new java.awt.Color(255, 255, 255));
        notificationBTN.setText("Notification");
        notificationBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        notificationBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notificationBTN.setFocusable(false);
        notificationBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationBTNMouseClicked(evt);
            }
        });
        notificationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBTNActionPerformed(evt);
            }
        });
        jPanel2.add(notificationBTN);
        notificationBTN.setBounds(75, 314, 119, 38);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Log Out");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(75, 379, 119, 38);

        notificationCountValue.setText("0");
        notificationCountValue.setBorder(null);
        notificationCountValue.setEnabled(false);
        notificationCountValue.setFocusable(false);
        jPanel2.add(notificationCountValue);
        notificationCountValue.setBounds(190, 300, 40, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 280, 1090);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Admin Dashboard");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 30, 370, 80);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Total number of banned users :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(790, 100, 250, 20);

        totalNumberOfBannedUser.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        totalNumberOfBannedUser.setText("0");
        jPanel1.add(totalNumberOfBannedUser);
        totalNumberOfBannedUser.setBounds(1050, 100, 70, 20);

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("Total number of user, using the service :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 100, 350, 20);

        totalNumberOfUser.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jPanel1.add(totalNumberOfUser);
        totalNumberOfUser.setBounds(660, 100, 70, 20);

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setText("Total number of files uploaded :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(330, 130, 260, 20);

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setText("Total number of files uploaded :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(330, 130, 250, 20);

        totalNumberOfFilesUploaded.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        totalNumberOfFilesUploaded.setText("0");
        jPanel1.add(totalNumberOfFilesUploaded);
        totalNumberOfFilesUploaded.setBounds(590, 130, 70, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12982910_5124556.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-140, 210, 2060, 1010);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBTNActionPerformed
        // TODO add your handling code here:
      new NotificationDashboard().setVisible(true);
      new FetchReportedUserData().fetchReportUserData();
    }//GEN-LAST:event_notificationBTNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new AllFilesTable().setVisible(true);   
        new FetchFilesDataForTable().fetchFilesDataForTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AllUserTable().setVisible(true);
        new FetchUserDataForTable().fetchUserDataForTable();
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void notificationBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationBTNMouseClicked
        // TODO add your handling code here:
         new FetchReportedUserData().fetchReportUserData();
    }//GEN-LAST:event_notificationBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminDashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton notificationBTN;
    public static javax.swing.JButton notificationCountValue;
    private static javax.swing.JLabel totalNumberOfBannedUser;
    private static javax.swing.JLabel totalNumberOfFilesUploaded;
    private static javax.swing.JLabel totalNumberOfUser;
    // End of variables declaration//GEN-END:variables
    public static void getAnalytics(String totalUser, String totalFiles, String total_BannedUser){
       totalNumberOfUser.setText(totalUser);
       totalNumberOfFilesUploaded.setText(totalFiles);
       totalNumberOfBannedUser.setText(total_BannedUser);
    }
 }

