/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.fetchUserOwnedPost;

/**
 *
 * @author jaint
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        dashBoard = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codeSnippets = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        myProfile = new javax.swing.JButton();
        userRealName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uplodeCodeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        postContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1910, 1080));
        getContentPane().setLayout(null);

        dashBoard.setBackground(new java.awt.Color(255, 255, 255));
        dashBoard.setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(16, 23, 39));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Byte Stack");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home.png"))); // NOI18N
        jLabel3.setText("Home");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        codeSnippets.setBackground(new java.awt.Color(16, 23, 39));
        codeSnippets.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        codeSnippets.setForeground(new java.awt.Color(255, 255, 255));
        codeSnippets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/code.png"))); // NOI18N
        codeSnippets.setText("Code snippets");
        codeSnippets.setToolTipText("View your code snippets");
        codeSnippets.setBorder(null);
        codeSnippets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        codeSnippets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeSnippetsActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(16, 23, 39));
        logOutBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/exit.png"))); // NOI18N
        logOutBtn.setText("Log out");
        logOutBtn.setToolTipText("log out from your account");
        logOutBtn.setBorder(null);
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        myProfile.setBackground(new java.awt.Color(16, 23, 39));
        myProfile.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        myProfile.setForeground(new java.awt.Color(255, 255, 255));
        myProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        myProfile.setText("My Profile");
        myProfile.setToolTipText("View your profile");
        myProfile.setBorder(null);
        myProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(myProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeSnippets, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(207, 207, 207)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(myProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(codeSnippets, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dashBoard.add(jPanel1);
        jPanel1.setBounds(0, 0, 290, 1080);

        userRealName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        userRealName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashBoard.add(userRealName);
        userRealName.setBounds(450, 80, 700, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel9.setText("Welcome");
        dashBoard.add(jLabel9);
        jLabel9.setBounds(330, 90, 110, 30);

        uplodeCodeBtn.setBackground(new java.awt.Color(0, 51, 255));
        uplodeCodeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uplodeCodeBtn.setForeground(new java.awt.Color(255, 255, 255));
        uplodeCodeBtn.setText("Uplode code snippet");
        uplodeCodeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        uplodeCodeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uplodeCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplodeCodeBtnActionPerformed(evt);
            }
        });
        dashBoard.add(uplodeCodeBtn);
        uplodeCodeBtn.setBounds(1280, 80, 170, 40);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        postContainer.setBackground(new java.awt.Color(255, 255, 255));
        postContainer.setPreferredSize(new java.awt.Dimension(1920, 1080));
        postContainer.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(postContainer);

        dashBoard.add(jScrollPane1);
        jScrollPane1.setBounds(290, 230, 1250, 560);

        getContentPane().add(dashBoard);
        dashBoard.setBounds(0, 0, 1620, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uplodeCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplodeCodeBtnActionPerformed
        // TODO add your handling code here:
       UplodeFilePage ufp = new UplodeFilePage();
       ufp.setVisible(true);
    }//GEN-LAST:event_uplodeCodeBtnActionPerformed

    private void codeSnippetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeSnippetsActionPerformed
        // TODO add your handling code here:
      new UserSnippets().setVisible(true);
        try {
            new fetchUserOwnedPost().fetchUserPostPanels();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_codeSnippetsActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void myProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton codeSnippets;
    private javax.swing.JDesktopPane dashBoard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton myProfile;
    public static javax.swing.JPanel postContainer;
    private javax.swing.JButton uplodeCodeBtn;
    private javax.swing.JLabel userRealName;
    // End of variables declaration//GEN-END:variables

    public void fetchName(String realname){
        String s = realname;
        userRealName.setText(s);
        System.out.print("Indashboard" + " "+ s);
    }
}

