/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author jaint
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        HomePage = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        loginBtnAbove = new javax.swing.JButton();
        headingBigLeft = new javax.swing.JLabel();
        headingBigLeft1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GetStartedBtn = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        logInExisting = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Byte Stack");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setName("HomePageFrameContainer"); // NOI18N

        HomePage.setBackground(new java.awt.Color(255, 255, 255));
        HomePage.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        HomePage.add(jLabel1);
        jLabel1.setBounds(20, 18, 174, 68);

        loginBtnAbove.setBackground(new java.awt.Color(51, 51, 255));
        loginBtnAbove.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        loginBtnAbove.setForeground(new java.awt.Color(255, 255, 255));
        loginBtnAbove.setText("Log In");
        loginBtnAbove.setToolTipText("Login into existing account");
        loginBtnAbove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtnAbove.setBorderPainted(false);
        loginBtnAbove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtnAbove.setFocusPainted(false);
        loginBtnAbove.setFocusable(false);
        loginBtnAbove.setName("loginAboveBtn"); // NOI18N
        loginBtnAbove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnAboveActionPerformed(evt);
            }
        });
        HomePage.add(loginBtnAbove);
        loginBtnAbove.setBounds(1330, 40, 116, 36);

        headingBigLeft.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        headingBigLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingBigLeft.setText("Explore, and Collaborate with code snippets");
        HomePage.add(headingBigLeft);
        headingBigLeft.setBounds(80, 320, 513, 58);
        headingBigLeft.getAccessibleContext().setAccessibleName("");

        headingBigLeft1.setFont(new java.awt.Font("Eras Light ITC", 0, 48)); // NOI18N
        headingBigLeft1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingBigLeft1.setText("Welcome to Byte Stack");
        HomePage.add(headingBigLeft1);
        headingBigLeft1.setBounds(80, 270, 513, 64);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/undraw_fun-underline (2).png"))); // NOI18N
        HomePage.add(jLabel2);
        jLabel2.setBounds(460, 340, 90, 60);

        GetStartedBtn.setBackground(new java.awt.Color(102, 102, 255));
        GetStartedBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        GetStartedBtn.setForeground(new java.awt.Color(255, 255, 255));
        GetStartedBtn.setText("Get Started");
        GetStartedBtn.setToolTipText("Register with a new account");
        GetStartedBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GetStartedBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GetStartedBtn.setFocusable(false);
        GetStartedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetStartedBtnActionPerformed(evt);
            }
        });
        HomePage.add(GetStartedBtn);
        GetStartedBtn.setBounds(120, 450, 420, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/undraw_Programmer_re_owql.png"))); // NOI18N
        HomePage.add(jLabel4);
        jLabel4.setBounds(730, 110, 730, 650);

        logInExisting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logInExisting.setText("Or log in with existing account");
        logInExisting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logInExisting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logInExistingMousePressed(evt);
            }
        });
        HomePage.add(logInExisting);
        logInExisting.setBounds(240, 610, 170, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 2186, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnAboveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnAboveActionPerformed
        // TODO add your handling code here:
        LoginPage loginpage = new LoginPage();
        loginpage.setVisible(true);
    }//GEN-LAST:event_loginBtnAboveActionPerformed

    private void GetStartedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetStartedBtnActionPerformed
        // TODO add your handling code here:
        RegisterPage RegisterPage = new RegisterPage();
        RegisterPage.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_GetStartedBtnActionPerformed

    private void logInExistingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInExistingMousePressed
        // TODO add your handling code here:
        LoginPage loginpage = new LoginPage();
        loginpage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logInExistingMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton GetStartedBtn;
    private javax.swing.JDesktopPane HomePage;
    private javax.swing.JLabel headingBigLeft;
    private javax.swing.JLabel headingBigLeft1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel logInExisting;
    private javax.swing.JButton loginBtnAbove;
    // End of variables declaration//GEN-END:variables
}
