/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.DownloadFile;
import model.RegisterLikes;
import model.RegisterReport;
import model.TokenManager;

/**
 *
 * @author jaint
 */
public class PostStructure extends javax.swing.JPanel {
      int code_ID;
    /**
     * Creates new form PostStructure
     */
    public PostStructure( String postTitle, String postDescription, String postLikes, String date, String language, String username , int code_id, String textData) {
        initComponents();
        String pt = postTitle;
        String pd = postDescription;
        String pl = postLikes;
        String pdate = date;
        code_ID = code_id;
        String fileContent = textData;

        
        System.out.println(pt);
        System.out.println(pd);
        System.out.println(pl);
        System.out.println("");
        
        PostTitle.setText(pt);
        PostDescription.setText(pd);
        PostLikes.setText(pl);
        DateOfUpload.setText(date);
        languageBtn.setText(language);
        PostAuthorName.setText(username);
        fileArea.setText(fileContent);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PostTitle = new javax.swing.JLabel();
        PostAuthorName = new javax.swing.JLabel();
        PostDescription = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PostLikes = new javax.swing.JLabel();
        DateOfUpload = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        likeButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        reportBtn = new javax.swing.JButton();
        languageBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileArea = new javax.swing.JTextArea();
        downloadBtn1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(549, 300));
        setLayout(null);

        PostTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        PostTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PostTitle.setText("Title for code snippet file");
        PostTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(PostTitle);
        PostTitle.setBounds(20, 70, 370, 20);

        PostAuthorName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PostAuthorName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        PostAuthorName.setText("Tushar Jain");
        add(PostAuthorName);
        PostAuthorName.setBounds(20, 20, 370, 30);

        PostDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PostDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PostDescription.setText("Description for the code snippet file");
        PostDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(PostDescription);
        PostDescription.setBounds(20, 100, 500, 20);

        jPanel1.setBackground(new java.awt.Color(54, 82, 173));
        jPanel1.setLayout(null);

        PostLikes.setForeground(new java.awt.Color(255, 255, 255));
        PostLikes.setText("Likes :");
        jPanel1.add(PostLikes);
        PostLikes.setBounds(70, 20, 32, 16);

        DateOfUpload.setBackground(new java.awt.Color(255, 255, 255));
        DateOfUpload.setForeground(new java.awt.Color(255, 255, 255));
        DateOfUpload.setText("Uploded :");
        jPanel1.add(DateOfUpload);
        DateOfUpload.setBounds(350, 20, 160, 16);
        jPanel1.add(filler1);
        filler1.setBounds(270, 50, 0, 0);

        likeButton.setBackground(new java.awt.Color(204, 204, 204));
        likeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thumb-up.png"))); // NOI18N
        likeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        likeButton.setFocusable(false);
        likeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(likeButton);
        likeButton.setBounds(20, 10, 40, 31);

        add(jPanel1);
        jPanel1.setBounds(0, 400, 550, 50);
        add(filler2);
        filler2.setBounds(270, 240, 0, 0);

        reportBtn.setBackground(new java.awt.Color(255, 51, 51));
        reportBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reportBtn.setForeground(new java.awt.Color(255, 255, 255));
        reportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/sad-face.png"))); // NOI18N
        reportBtn.setText("Report");
        reportBtn.setBorder(null);
        reportBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportBtn.setFocusable(false);
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });
        add(reportBtn);
        reportBtn.setBounds(430, 20, 100, 24);

        languageBtn.setBackground(new java.awt.Color(204, 204, 255));
        languageBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        languageBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        languageBtn.setText("Language");
        languageBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Programming Language Used"));
        add(languageBtn);
        languageBtn.setBounds(330, 290, 210, 50);

        fileArea.setEditable(false);
        fileArea.setColumns(20);
        fileArea.setRows(5);
        jScrollPane1.setViewportView(fileArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(20, 120, 300, 260);

        downloadBtn1.setBackground(new java.awt.Color(204, 255, 204));
        downloadBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        downloadBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/download (1).png"))); // NOI18N
        downloadBtn1.setText("Download");
        downloadBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        downloadBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downloadBtn1.setFocusable(false);
        downloadBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadBtn1ActionPerformed(evt);
            }
        });
        add(downloadBtn1);
        downloadBtn1.setBounds(330, 350, 210, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void likeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeButtonActionPerformed
        // TODO add your handling code here:
           new RegisterLikes().addLike(TokenManager.getToken(),code_ID);
    }//GEN-LAST:event_likeButtonActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        new RegisterReport().registerReport(code_ID,PostTitle.getText());
    }//GEN-LAST:event_reportBtnActionPerformed

    private void downloadBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadBtn1ActionPerformed
        // TODO add your handling code here:
        new DownloadFile().downloadFile(code_ID);
    }//GEN-LAST:event_downloadBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfUpload;
    private javax.swing.JLabel PostAuthorName;
    private javax.swing.JLabel PostDescription;
    public static javax.swing.JLabel PostLikes;
    private javax.swing.JLabel PostTitle;
    private javax.swing.JButton downloadBtn1;
    private javax.swing.JTextArea fileArea;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel languageBtn;
    private javax.swing.JButton likeButton;
    private javax.swing.JButton reportBtn;
    // End of variables declaration//GEN-END:variables
    
}
