/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.RegisterPageController;

/**
 *
 * @author jaint
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterPage = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        securityAnswerField = new javax.swing.JTextField();
        securityQuestionField = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        createPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stack Byte");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        RegisterPage.setBackground(new java.awt.Color(255, 255, 255));
        RegisterPage.setMaximumSize(new java.awt.Dimension(1920, 1080));
        RegisterPage.setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 1080));
        jPanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/sign-up-form.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 150, 500, 590);

        RegisterPage.add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 990);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Last name");
        RegisterPage.add(jLabel1);
        jLabel1.setBounds(1170, 170, 210, 40);

        lastnameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });
        RegisterPage.add(lastnameField);
        lastnameField.setBounds(1170, 210, 250, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Answer your security question");
        RegisterPage.add(jLabel2);
        jLabel2.setBounds(860, 440, 210, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("First name");
        RegisterPage.add(jLabel3);
        jLabel3.setBounds(860, 170, 210, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Select your security question");
        RegisterPage.add(jLabel4);
        jLabel4.setBounds(1170, 350, 210, 40);

        firstnameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });
        RegisterPage.add(firstnameField);
        firstnameField.setBounds(860, 210, 250, 50);

        securityAnswerField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        securityAnswerField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        securityAnswerField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        securityAnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAnswerFieldActionPerformed(evt);
            }
        });
        RegisterPage.add(securityAnswerField);
        securityAnswerField.setBounds(860, 480, 250, 50);

        securityQuestionField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What was the name of your first school ?", "What is name of your best friend ?", "What is your birthday month ?" }));
        securityQuestionField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        securityQuestionField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterPage.add(securityQuestionField);
        securityQuestionField.setBounds(1170, 390, 250, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Confirm your password");
        RegisterPage.add(jLabel5);
        jLabel5.setBounds(860, 350, 210, 40);

        confirmPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });
        RegisterPage.add(confirmPasswordField);
        confirmPasswordField.setBounds(860, 390, 250, 50);

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        RegisterPage.add(usernameField);
        usernameField.setBounds(860, 300, 250, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Create a username");
        RegisterPage.add(jLabel7);
        jLabel7.setBounds(860, 260, 210, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Create a password");
        RegisterPage.add(jLabel8);
        jLabel8.setBounds(1170, 260, 210, 40);

        registerBtn.setBackground(new java.awt.Color(51, 102, 255));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.setBorder(null);
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        RegisterPage.add(registerBtn);
        registerBtn.setBounds(860, 590, 250, 50);

        createPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        createPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPasswordFieldActionPerformed(evt);
            }
        });
        RegisterPage.add(createPasswordField);
        createPasswordField.setBounds(1170, 300, 250, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Welcome to Byte Stack");
        RegisterPage.add(jLabel6);
        jLabel6.setBounds(1020, 60, 270, 80);

        getContentPane().add(RegisterPage);
        RegisterPage.setBounds(0, 0, 1770, 1090);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void securityAnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAnswerFieldActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        new RegisterPageController().getRegisterFormData(firstnameField.getText(), lastnameField.getText(), usernameField.getText(), createPasswordField.getText(), confirmPasswordField.getText(),securityQuestionField.getSelectedItem().toString(), securityAnswerField.getText());
    }//GEN-LAST:event_registerBtnActionPerformed

    private void createPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane RegisterPage;
    private javax.swing.JTextField confirmPasswordField;
    private javax.swing.JPasswordField createPasswordField;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField securityAnswerField;
    private javax.swing.JComboBox<String> securityQuestionField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
