/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.FileUploadPgeController;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author jaint
 */
public class UplodeFilePage extends javax.swing.JDialog {

    /**
     * Creates new form UplodeFilePage
     */
    public UplodeFilePage() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        languageSelector = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileDescriptionTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        fileTitleTextField = new javax.swing.JTextField();
        uplodeFileBTn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Byte Satck - File upload");
        setBounds(new java.awt.Rectangle(480, 180, 0, 0));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(730, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Uplode file");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(40, 20, 100, 25);

        fileChooser.setBackground(new java.awt.Color(249, 249, 249));
        fileChooser.setDialogTitle("Select a file to uplode");
        jDesktopPane1.add(fileChooser);
        fileChooser.setBounds(30, 40, 430, 520);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("File description");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(480, 110, 100, 20);

        languageSelector.setBackground(new java.awt.Color(249, 249, 249));
        languageSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C++", "C", "JAVA", "PYTHON", ".NET", "HTML", "CSS", "JAVASCRIPT", "REACT", "RUST", "SQL" }));
        jDesktopPane1.add(languageSelector);
        languageSelector.setBounds(480, 330, 98, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("File title");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(480, 50, 50, 20);

        fileDescriptionTextArea.setBackground(new java.awt.Color(249, 249, 249));
        fileDescriptionTextArea.setColumns(20);
        fileDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(fileDescriptionTextArea);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 140, 230, 150);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Language");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(480, 300, 80, 20);

        fileTitleTextField.setBackground(new java.awt.Color(249, 249, 249));
        fileTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTitleTextFieldActionPerformed(evt);
            }
        });
        jDesktopPane1.add(fileTitleTextField);
        fileTitleTextField.setBounds(480, 70, 170, 30);

        uplodeFileBTn.setBackground(new java.awt.Color(51, 51, 255));
        uplodeFileBTn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uplodeFileBTn.setForeground(new java.awt.Color(255, 255, 255));
        uplodeFileBTn.setText("Uplode");
        uplodeFileBTn.setBorder(null);
        uplodeFileBTn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uplodeFileBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplodeFileBTnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(uplodeFileBTn);
        uplodeFileBTn.setBounds(520, 450, 160, 50);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 750, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileTitleTextFieldActionPerformed

    private void uplodeFileBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplodeFileBTnActionPerformed
        // TODO add your handling code here:
        FileUploadPgeController fupc = new FileUploadPgeController();
        File f = fileChooser.getSelectedFile();
        String path = f.getAbsolutePath();
        System.out.println(path);
        fupc.getFileContent(fileTitleTextField.getText(),fileDescriptionTextArea.getText(),languageSelector.getSelectedItem().toString(),path);
    }//GEN-LAST:event_uplodeFileBTnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UplodeFilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UplodeFilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UplodeFilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UplodeFilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UplodeFilePage dialog = new UplodeFilePage();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextArea fileDescriptionTextArea;
    private javax.swing.JTextField fileTitleTextField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> languageSelector;
    private javax.swing.JButton uplodeFileBTn;
    // End of variables declaration//GEN-END:variables

}
