/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.ImposeBan;

/**
 *
 * @author jaint
 */
public class userDetailsStructure extends javax.swing.JPanel {

    /**
     * Creates new form userDetailsStructure
     */
    String u,s,r;
    public userDetailsStructure(String Username, String Role, String state) {
        initComponents();
         u = Username;
         r = Role;
         s = state;
        
        username.setText(u);
        state1.setText(s);
        role.setText(r);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        state1 = new javax.swing.JLabel();
        banUserBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(null);

        username.setText("jLabel1");
        add(username);
        username.setBounds(30, 30, 210, 30);

        role.setText("jLabel1");
        add(role);
        role.setBounds(30, 100, 127, 34);

        state1.setText("jLabel1");
        add(state1);
        state1.setBounds(30, 60, 127, 34);

        banUserBtn.setBackground(new java.awt.Color(204, 0, 51));
        banUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        banUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        banUserBtn.setText("BAN USER");
        banUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banUserBtnMouseClicked(evt);
            }
        });
        banUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banUserBtnActionPerformed(evt);
            }
        });
        add(banUserBtn);
        banUserBtn.setBounds(150, 150, 130, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void banUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banUserBtnActionPerformed

    private void banUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banUserBtnMouseClicked
        // TODO add your handling code here:
        new ImposeBan().imposeBan(u);
        
    }//GEN-LAST:event_banUserBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton banUserBtn;
    private javax.swing.JLabel role;
    private javax.swing.JLabel state1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
